[2022-08-30 12:58:58,938]^;INFO^;100^;configuration.py^;get_training_pipeline_config^;Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\HP\\Desktop\\Credit Card Default Prediction\\Credit-Card-Default-Prediction-ML-Project\\CreditCard_Defaults\\artifact')
[2022-08-30 12:58:58,938]^;ERROR^;13^;test.py^;main^;Error occured in script: [C:\Users\HP\Desktop\Credit Card Default Prediction\Credit-Card-Default-Prediction-ML-Project\CreditCard_Defaults\pipeline\pipeline.py] at line number: [48]. Error message is: [Error occured in script: [C:\Users\HP\Desktop\Credit Card Default Prediction\Credit-Card-Default-Prediction-ML-Project\CreditCard_Defaults\pipeline\pipeline.py] at line number: [41]. Error message is: ['Configuration' object has no attribute 'get_data_ingestion_config']]
